[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "mplchart"
version = "0.0.6"
requires-python = ">=3.9"
readme = "output/README.md"
description = "Classic Stock Charts in Python"
license = { text = "MIT" }
urls = { homepage = "https://github.com/furechan/mplchart" }
authors = [{ name = "Furechan", email = "furechan@xsmail.com" }]
keywords = ["finance", "charting", "matplotlib", "candlesticks"]
dependencies = ["matplotlib", "yfinance", "numpy", "pandas"]
optional-dependencies.dev = ["pytest", "ipykernel"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.hatch.build]
targets.wheel.sources = ["src"]
dev-mode-dirs = ["src"]
only-include = ["src"]
exclude = [".*"]

[tool.pydev]
allow-publish = true

[tool.pytest.ini_options]
filterwarnings = ["ignore", "default:::mplchart"]
addopts = ["-p no:cacheprovider"]
testpaths = ["tests"]
